# Generated by Django 2.1.7 on 2019-03-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_locked',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
